/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

/**
 *
 * @author Usuario
 */
public class desproteger extends javax.swing.JFrame {

    /**
     * Creates new form desproteger
     */
    public desproteger() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        protegerB = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        textArea2 = new java.awt.TextArea();
        textArea1 = new java.awt.TextArea();
        aux0 = new javax.swing.JPanel();
        tituloHamming = new javax.swing.JLabel();
        exitB = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();
        fondo4 = new javax.swing.JLabel();
        fondo0 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(975, 562));
        setSize(new java.awt.Dimension(562, 972));

        background.setBackground(new java.awt.Color(28, 40, 61));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 26, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jPanel2.setBackground(new java.awt.Color(18, 26, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(28, 40, 61));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-con-llave (2).png"))); // NOI18N

        protegerB.setBackground(new java.awt.Color(18, 26, 51));
        protegerB.setFont(new java.awt.Font("Roboto Cn", 0, 22)); // NOI18N
        protegerB.setForeground(new java.awt.Color(255, 255, 255));
        protegerB.setText("DESPROTEGER");
        protegerB.setBorder(null);
        protegerB.setMaximumSize(new java.awt.Dimension(336, 36));
        protegerB.setMinimumSize(new java.awt.Dimension(336, 36));
        protegerB.setPreferredSize(new java.awt.Dimension(336, 36));
        protegerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                protegerBMouseClicked(evt);
            }
        });
        protegerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protegerBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(protegerB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(protegerB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jPanel6.setBackground(new java.awt.Color(28, 40, 61));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 183, 246));
        jLabel2.setText("CORREGIR:");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(10, 12, 110, 20);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton2.setText("Seleccionar archivo (.HAx, .HEx)");
        jPanel6.add(jButton2);
        jButton2.setBounds(690, 10, 260, 30);

        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("NO");
        jPanel6.add(jRadioButton1);
        jRadioButton1.setBounds(160, 10, 50, 24);

        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("SI");
        jPanel6.add(jRadioButton2);
        jRadioButton2.setBounds(120, 10, 40, 24);

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 50));
        jPanel2.add(textArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 320));
        jPanel2.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 320, 320));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, 410));

        aux0.setBackground(new java.awt.Color(0, 0, 0));

        tituloHamming.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        tituloHamming.setForeground(new java.awt.Color(218, 236, 255));
        tituloHamming.setText("DESPROTEGER ARCHIVO");
        tituloHamming.setToolTipText("");

        javax.swing.GroupLayout aux0Layout = new javax.swing.GroupLayout(aux0);
        aux0.setLayout(aux0Layout);
        aux0Layout.setHorizontalGroup(
            aux0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamming, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        aux0Layout.setVerticalGroup(
            aux0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamming, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        background.add(aux0, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 600, 50));

        exitB.setBackground(new java.awt.Color(18, 26, 51));
        exitB.setFont(new java.awt.Font("Roboto Slab", 0, 16)); // NOI18N
        exitB.setForeground(new java.awt.Color(255, 255, 255));
        exitB.setText("SALIR");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });
        background.add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 90, 30));

        volver.setBackground(new java.awt.Color(18, 26, 51));
        volver.setFont(new java.awt.Font("Roboto Slab", 0, 15)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.gif"))); // NOI18N
        fondo2.setText("jLabel6");
        background.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 650, 320));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.gif"))); // NOI18N
        fondo3.setText("jLabel6");
        background.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 600, 80));

        fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.gif"))); // NOI18N
        fondo4.setText("jLabel6");
        background.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 580, 70));

        fondo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.gif"))); // NOI18N
        fondo0.setText("jLabel6");
        background.add(fondo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 580, 70));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.gif"))); // NOI18N
        fondo1.setText("jLabel6");
        background.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 20, 580, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        main m = new main();
        this.dispose();
        m.setVisible(true);

    }//GEN-LAST:event_volverMouseClicked

    private void protegerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protegerBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protegerBActionPerformed

    private void protegerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerBMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_protegerBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desproteger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desproteger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desproteger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desproteger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desproteger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aux0;
    private javax.swing.JPanel background;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel fondo0;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton protegerB;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    private javax.swing.JLabel tituloHamming;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
